import 'package:get/get.dart';

class TranslationManager extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_EN': {
          "enter_phone": "Enter your phone number",
          "enter_phone_desc":
              "Please enter your phone number. You will\nreceive a verification code.",
          "enter_code_desc":
              "We have sent a code. enter it to verify\nyour phone number : 0",
          "enter_name": "Enter your name",
          "enter_name_desc":
              "Welcome to wassla, one more step\nand make your deliveries",
          "home": "Home",
          "history": "History",
          "profile": "Profile",
          "deliveries": "Deliveries",
          "next": "Next",
          "start_by_clicking": "Start by clicking the input below",
          "start": "Start",
          "done": "Done",
          "send": "Send",
          "validate": "Validate",
          "save": "Save",
          "okay": "OKay",
          "resend": "Resend",
          "apply": "APPLY",
          "submit": "Submit",
          "filed": "Filed",
          "success": "Success",
          "error_something": "Something went wrong",
          "operation_done": "Operation done",
          "code_sent_phone": "Code sent to your phone number",
          "profile_updated": "Profile updated",
          "no_deliveries": "You have no deliveries!",
          "no_tickets": "You have no tickets!",
          "gender": "Gender",
          "first_name": "First name",
          "family_name": "Family name",
          "full_name": "Full name",
          "email": "Email",
          "review": "Review",
          "birth_date": "Birth date",
          "promo_code": "Promo code",
          "phone_number": "Phone number",
          "package_address": "Package address",
          "title": "Title",
          "message": "Message",
          "level": "Level",
          "section": "Section",
          "first_name_required": "First name is required",
          "family_name_required": "Family name is required",
          "valid_first_name": "Please type a valid name",
          "valid_family_name": "Please type a valid name",
          "valid_title": "Title is required",
          "valid_content": "Content is required",
          "title_short": "Title is too short",
          "title_long": "Title is too long",
          "content_short": "Content is too short",
          "content_long": "Content is too long",
          "resend_after": "Resend after : ",
          "wassla_service": "You need wassla delivery service?",
          "click": "Start by clicking the input below",
          "chat": "Chat",
          "no_messages": "No messages for now",
          "customize_delivery": "Customize your delivery",
          "history_search": "History search",
          "your_address": "Your address",
          "description": "Description",
          "use_current_location": "Use current location",
          "choose_map": "Choose on the map",
          "result_search": "Result search",
          "delivery_accepted": "The courier is on the way to take the package",
          "delivery_recovered": "The courier is on the way to you",
          "delivery_delivered": "The courier arrived",
          "give_code": "Give this code to the delivery: ",
          "previous_delivery": "Previous delivery",
          "canceled": "Canceled",
          "finished": "Finished",
          "delivering": "Delivering",
          "appreciate_service":
              "We appreciate your trust in our service. 🛒 We hope to see you again soon! 😊",
          "thank_you": "Thank You! 🙏",
          "in_your_area": "In your area",
          "select_delivery_method": "Select the delivery method",
          "wassla_search": "Wassla search",
          "please_wait":
              "Please wait a moment, we are looking for the closest delivery to you",
          "itinerary": "Itinerary",
          "price": "Price",
          "cash_payment": "CASH PAYMENT",
          "options": "Options",
          "cancel_ride": "Cancel ride",
          "promo_code_title": "PROMO CODE",
          "promo_code_desc":
              "Unlock exclusive discounts! Enter your promo code below to enjoy special savings on your next order",
          "new_ticket": "New ticket",
          "close_ticket_title": "Close ticket",
          "close_ticket_desc":
              "You are about to close this ticket. Once this operation is completed, it cannot be undone. Are you sure you want to proceed?",
          "tickets": "Tickets",
          "close": "Close",
          "add_response": "Add response",
          "new_message": "New message",
          "choose_destination": "Choose your destination",
          "log_out": "Log out",
          "my_profile": "My Profile",
          "partner_with_us": "Partner with us",
          "contact_us": "Contact us",
          "report_issue": "Report an issue",
          "terms_conditions": "Terms & conditions",
          "rate": "Rate",
          "more": "More",
          "delete_account": "Delete account",
          "delete_no_longer_use": "I no longer use the app.",
          "delete_found_alternative": "I found a better alternative.",
          "delete_multiple_accounts": "I have multiple accounts.",
          "delete_technical_issues": "I am experiencing technical issues.",
          "delete_difficult_use": "I find the app difficult to use.",
          "delete_not_useful": "I don’t find the app useful anymore.",
          "delete_missing_features":
              "The app doesn’t have the features I need.",
          "delete_different_service": "I’m switching to a different service.",
          "delete_reduce_screen_time": "I’m trying to reduce my screen time.",
          "delete_achieved_goals": "I’ve achieved my goals with the app.",
          "delete_other": "Other.",
          "account_deactivated": "Your account has been deactivated.",
          "deactivation_decision":
              "If you believe this decision is not justified, please contact us.",
          "deactivation_reason":
              "Your account has been deactivated for these reasons: ",
          "courier_information": "Courier formations",
          "date_price": "Date & Price",
          "delivery_id": "Delivery id: ",
          "package_details": "Package details",
          "delivery_details": "Delivery details",
          "male": "Male",
          "female": "Female",
          "accepted": "Accepted",
          "recovered": "Recovered",
          "delivered": "Delivered",
          "onFeet": "On feet",
          "car": "Car",
          "bicycle": "Bicycle",
          "motorcycle": "Motorcycle",
          "open": "Open",
          "closed": "Closed",
          "low": "Low",
          "high": "High",
          "medium": "Medium",
          "you": "You",
          "support": "Support",
          "delivery": "Delivery",
          "account": "Account",
          "subscription": "Subscription",
          "others": "Others",
          "code_sent": "Code sent",
          "retryButton": "Retry",
          "conTryAgain": "Check your connection and try again",
          "tryAgain": "Try again",
          "connectionFailed": "Connection failed",
          "updateRequiredTitle": "Update required",
          "updateButton": "Update",
          "updateRequiredDesc":
              "A new version of this application is available. Please update to continue using it.",
          "cancelDelivery": "Cancel delivery",
          "whyCancel": "Why do you want to cancel this delivery?",
          'cancelRequest': 'Cancel delivery request',
          'cancelRequestDesc': 'Are you sure you want to cancel the delivery?',
          'cancelDeliveryDesc':
              'Are you sure you want to cancel the delivery? Repeated cancellations may result in your account being temporarily deactivated.',
          'cancelDeliveryChangeMind': 'Changed my mind',
          'cancelDeliveryLong': 'Delivery taking too long',
          'cancelDeliveryAddressIncorrect': 'Delivery address is incorrect',
          'cancelDeliveryPackageNoNeeded': 'Package no longer needed',
          'cancelDeliveryIncorrectItem': 'Incorrect items in the order',
          'cancelDeliveryMySelf': 'Prefer to pick it up myself',
          'cancelDeliveryOther': 'Other',
          'goBackButton': 'Go back',
          'confirmButton': 'Confirm',
          'deliveryCanceled': 'Delivery canceled',
          'deliveryCanceledDesc':
              'The delivery has been canceled by the client. If you encountered any issues, you can report them for further assistance.',
          'callCourier': 'Call courier',
          'callCourierDesc':
              'You are about to make a phone call with the courier.',
          'callButton': 'Call',
          'copyNumber': 'Copy',
        },
        'fr_FR': {
          // Titles and Descriptions
          "enter_phone": "Entrez votre numéro de téléphone",
          "enter_phone_desc":
              "Veuillez entrer votre numéro de téléphone. Vous recevrez un code de vérification.",
          "enter_code_desc":
              "Nous avons envoyé un code. Entrez-le pour vérifier votre numéro de téléphone : 0",
          "enter_name": "Entrez votre nom",
          "enter_name_desc":
              "Bienvenue sur Wassla, une étape de plus et vous pourrez faire vos livraisons",
          "home": "Accueil",
          "history": "Historique",
          "profile": "Profil",
          "deliveries": "Livraisons",
          "next": "Suivant",
          "start_by_clicking": "Commencez en cliquant sur la bare inférieure",
          "start": "S'inscrire",
          "done": "Fait",
          "send": "Envoyer",
          "validate": "Valider",
          "save": "Enregistrer",
          "okay": "D'accord",
          "resend": "Renvoyer",
          "apply": "Appliquer",
          "submit": "Soumettre",
          "filed": "Echec",
          "success": "Succès",
          "error_something": "Une erreur est survenue",
          "operation_done": "Opération terminée",
          "code_sent_phone": "Code envoyé à votre numéro de téléphone",
          "profile_updated": "Profil mis à jour",
          "no_deliveries": "Vous n'avez aucune livraison !",
          "no_tickets": "Vous n'avez aucun ticket !",
          "gender": "Genre",
          "first_name": "Prénom",
          "family_name": "Nom de famille",
          "full_name": "Nom complet",
          "email": "Email",
          "review": "Avis",
          "birth_date": "Date de naissance",
          "promo_code": "Code promo",
          "phone_number": "Numéro de téléphone",
          "package_address": "Adresse du colis",
          "title": "Titre",
          "message": "Message",
          "level": "Niveau",
          "section": "Section",
          "first_name_required": "Le prénom est requis",
          "family_name_required": "Le nom de famille est requis",
          "valid_first_name": "Veuillez entrer un prénom valide",
          "valid_family_name": "Veuillez entrer un nom de famille valide",
          "valid_title": "Le titre est requis",
          "valid_content": "Le contenu est requis",
          "title_short": "Le titre est trop court",
          "title_long": "Le titre est trop long",
          "content_short": "Le contenu est trop court",
          "content_long": "Le contenu est trop long",
          "resend_after": "Renvoyer après : ",
          "wassla_service": "Vous avez besoin du service de livraison Wassla ?",
          "click": "Commencez en cliquant sur l'entrée ci-dessous",
          "chat": "Chat",
          "no_messages": "Aucun message pour l'instant",
          "customize_delivery": "Personnalisez votre livraison",
          "history_search": "Recherche d'historique",
          "your_address": "Votre adresse",
          "description": "Description",
          "use_current_location": "Utiliser la position actuelle",
          "choose_map": "Choisir sur la carte",
          "result_search": "Résultats de la recherche",
          "delivery_accepted": "Le coursier est en route pour prendre le colis",
          "delivery_recovered": "Le coursier est en route vers vous",
          "delivery_delivered": "Le coursier est arrivé",
          "give_code": "Donnez ce code au livreur : ",
          "previous_delivery": "Livraison précédente",
          "canceled": "Annulé",
          "finished": "Terminé",
          "delivering": "En livraison",
          "appreciate_service":
              "Nous apprécions votre confiance dans notre service. 🛒 Nous espérons vous revoir bientôt ! 😊",
          "thank_you": "Merci ! 🙏",
          "in_your_area": "Dans votre zone",
          "select_delivery_method": "Sélectionnez le mode de livraison",
          "wassla_search": "Recherche Wassla",
          "please_wait":
              "Veuillez patienter un moment, nous cherchons la livraison la plus proche de vous",
          "itinerary": "Itinéraire",
          "price": "Prix",
          "cash_payment": "PAIEMENT EN ESPÈCES",
          "options": "Options",
          "cancel_ride": "Annuler la course",
          "promo_code_title": "CODE PROMO",
          "promo_code_desc":
              "Déverrouillez des réductions exclusives ! Entrez votre code promo ci-dessous pour bénéficier d'économies spéciales sur votre prochaine commande",
          "new_ticket": "Nouveau ticket",
          "close_ticket_title": "Fermer le ticket",
          "close_ticket_desc":
              "Vous êtes sur le point de fermer ce ticket. Une fois cette opération effectuée, elle ne peut pas être annulée. Êtes-vous sûr de vouloir continuer ?",
          "tickets": "Tickets",
          "close": "Fermer",
          "add_response": "Ajouter une réponse",
          "new_message": "Nouveau message",
          "choose_destination": "Choisissez votre destination",
          "log_out": "Se déconnecter",
          "my_profile": "Mon profil",
          "partner_with_us": "Partenaire avec nous",
          "contact_us": "Contactez-nous",
          "report_issue": "Signaler un problème",
          "terms_conditions": "Conditions générales",
          "rate": "Évaluer",
          "more": "Plus",
          "delete_account": "Supprimer le compte",
          "delete_no_longer_use": "Je n'utilise plus l'application.",
          "delete_found_alternative": "J'ai trouvé une meilleure alternative.",
          "delete_multiple_accounts": "J'ai plusieurs comptes.",
          "delete_technical_issues": "Je rencontre des problèmes techniques.",
          "delete_difficult_use":
              "Je trouve l'application difficile à utiliser.",
          "delete_not_useful": "Je ne trouve plus l'application utile.",
          "delete_missing_features":
              "L'application n'a pas les fonctionnalités dont j'ai besoin.",
          "delete_different_service": "Je passe à un service différent.",
          "delete_reduce_screen_time": "J'essaie de réduire mon temps d'écran.",
          "delete_achieved_goals":
              "J'ai atteint mes objectifs avec l'application.",
          "delete_other": "Autre.",
          "account_deactivated": "Votre compte a été désactivé.",
          "deactivation_decision":
              "Si vous pensez que cette décision n'est pas justifiée, veuillez nous contacter.",
          "deactivation_reason":
              "Votre compte a été désactivé pour les raisons suivantes : ",
          "courier_information": "Informations sur le coursier",
          "date_price": "Date & Prix",
          "delivery_id": "ID de livraison : ",
          "package_details": "Détails du colis",
          "delivery_details": "Détails de la livraison",
          "male": "Homme",
          "female": "Femme",
          "accepted": "Accepté",
          "recovered": "Récupéré",
          "delivered": "Livré",
          "onFeet": "À pied",
          "car": "Voiture",
          "bicycle": "Vélo",
          "motorcycle": "Moto",
          "open": "Ouvert",
          "closed": "Fermé",
          "low": "Bas",
          "high": "Haut",
          "medium": "Moyen",
          "you": "vous",
          "support": "support",
          "delivery": "Livraison",
          "account": "Compte",
          "subscription": "Abonnement",
          "others": "Autres",
          "code_sent": "Code envoyé",
          "retryButton": "Réessayer",
          "conTryAgain": "Vérifiez votre connexion et réessayez",
          "tryAgain": "Réessayer",
          "connectionFailed": "Connexion échouée",
          "updateRequiredTitle": "Mise à jour requise",
          "updateButton": "Mettre à jour",
          "updateRequiredDesc":
              "Une nouvelle version de cette application est disponible. Veuillez mettre à jour pour continuer à l'utiliser.",
          "cancelDelivery": "Annuler la livraison",
          "whyCancel": "Pourquoi voulez-vous annuler cette livraison?",
          'cancelRequest': 'Annuler la demande de livraison',
          'cancelRequestDesc': 'Êtes-vous sûr de vouloir annuler la livraison?',
          'cancelDeliveryDesc':
              'Êtes-vous sûr de vouloir annuler la livraison? Les annulations répétées peuvent entraîner la désactivation temporaire de votre compte.',
          'cancelDeliveryChangeMind': 'J\'ai changé d\'avis',
          'cancelDeliveryLong': 'La livraison prend trop de temps',
          'cancelDeliveryAddressIncorrect': 'Adresse de livraison incorrecte',
          'cancelDeliveryPackageNoNeeded': 'Le colis n\'est plus nécessaire',
          'cancelDeliveryIncorrectItem': 'Articles incorrects dans la commande',
          'cancelDeliveryMySelf': 'Je préfère le récupérer moi-même',
          'cancelDeliveryOther': 'Autre',
          'goBackButton': 'Retour',
          'confirmButton': 'Confirmer',
          'deliveryCanceled': 'Livraison annulée',
          'deliveryCanceledDesc':
              'La livraison a été annulée par le client. Si vous avez rencontré des problèmes, vous pouvez les signaler pour obtenir une assistance supplémentaire.',
          'callCourier': 'Appeler le livreur',
          'callCourierDesc':
              'Vous êtes sur le point de passer un appel téléphonique avec le coursier.',
          'callButton': 'Appeler',
          'copyNumber': 'Copier',
        },
        'ar_AR': {
          // Titles and Descriptions
          "enter_phone": "أدخل رقم هاتفك",
          "enter_phone_desc": "يرجى إدخال رقم هاتفك. ستتلقى رمز التحقق.",
          "enter_code_desc": "لقد أرسلنا رمزًا. أدخله للتحقق من رقم هاتفك: 0",
          "enter_name": "أدخل اسمك",
          "enter_name_desc":
              "مرحبا بك في واسلة، خطوة واحدة أخرى وستتمكن من إجراء تسليماتك",
          "home": "الرئيسية",
          "history": "التاريخ",
          "profile": "الملف الشخصي",
          "deliveries": "التسليمات",
          "next": "التالي",
          "start_by_clicking": "ابدأ بالنقر على المدخل أدناه",
          "start": "ابدأ",
          "done": "تم",
          "send": "إرسال",
          "validate": "تحقق",
          "save": "حفظ",
          "okay": "موافق",
          "resend": "إعادة إرسال",
          "apply": "تطبيق",
          "submit": "إرسال",
          "filed": "مُقدّم",
          "success": "نجاح",
          "error_something": "حدث خطأ ما",
          "operation_done": "تمت العملية",
          "code_sent_phone": "تم إرسال الرمز إلى رقم هاتفك",
          "profile_updated": "تم تحديث الملف الشخصي",
          "no_deliveries": "لا توجد لديك تسليمات!",
          "no_tickets": "لا توجد لديك تذاكر!",
          "gender": "الجنس",
          "first_name": "الاسم الأول",
          "family_name": "اسم العائلة",
          "full_name": "الاسم الكامل",
          "email": "البريد الإلكتروني",
          "review": "مراجعة",
          "birth_date": "تاريخ الميلاد",
          "promo_code": "رمز ترويجي",
          "phone_number": "رقم الهاتف",
          "package_address": "عنوان الطرد",
          "title": "العنوان",
          "message": "رسالة",
          "level": "المستوى",
          "section": "القسم",
          "first_name_required": "الاسم الأول مطلوب",
          "family_name_required": "اسم العائلة مطلوب",
          "valid_first_name": "يرجى إدخال اسم صحيح",
          "valid_family_name": "يرجى إدخال اسم عائلة صحيح",
          "valid_title": "العنوان مطلوب",
          "valid_content": "المحتوى مطلوب",
          "title_short": "العنوان قصير جداً",
          "title_long": "العنوان طويل جداً",
          "content_short": "المحتوى قصير جداً",
          "content_long": "المحتوى طويل جداً",
          "resend_after": "إعادة الإرسال بعد: ",
          "wassla_service": "هل تحتاج إلى خدمة توصيل واسلة؟",
          "click": "ابدأ بالنقر على المدخل أدناه",
          "chat": "الدردشة",
          "no_messages": "لا توجد رسائل في الوقت الحالي",
          "customize_delivery": "خصص توصيلك",
          "history_search": "بحث في التاريخ",
          "your_address": "عنوانك",
          "description": "الوصف",
          "use_current_location": "استخدام الموقع الحالي",
          "choose_map": "اختر على الخريطة",
          "result_search": "نتائج البحث",
          "delivery_accepted": "المرسل في الطريق لاستلام الطرد",
          "delivery_recovered": "المرسل في الطريق إليك",
          "delivery_delivered": "المرسل وصل",
          "give_code": "اعط هذا الرمز للتوصيل: ",
          "previous_delivery": "التسليم السابق",
          "canceled": "ملغى",
          "finished": "منتهى",
          "delivering": "في التوصيل",
          "appreciate_service":
              "نحن نقدر ثقتك في خدمتنا. 🛒 نأمل أن نراك مرة أخرى قريبًا! 😊",
          "thank_you": "شكراً! 🙏",
          "in_your_area": "في منطقتك",
          "select_delivery_method": "اختر طريقة التوصيل",
          "wassla_search": "بحث واسلة",
          "please_wait": "يرجى الانتظار لحظة، نحن نبحث عن أقرب توصيل إليك",
          "itinerary": "الطريق",
          "price": "السعر",
          "cash_payment": "دفع نقدي",
          "options": "الخيارات",
          "cancel_ride": "إلغاء الرحلة",
          "promo_code_title": "رمز ترويجي",
          "promo_code_desc":
              "افتح خصومات حصرية! أدخل رمز الترويج الخاص بك أدناه للاستفادة من توفير خاص على طلبك القادم",
          "new_ticket": "تذكرة جديدة",
          "close_ticket_title": "إغلاق التذكرة",
          "close_ticket_desc":
              "أنت على وشك إغلاق هذه التذكرة. بمجرد إتمام هذه العملية، لا يمكن التراجع عنها. هل أنت متأكد أنك تريد المتابعة؟",
          "tickets": "التذاكر",
          "close": "إغلاق",
          "add_response": "أضف رد",
          "new_message": "رسالة جديدة",
          "choose_destination": "اختر وجهتك",
          "log_out": "تسجيل الخروج",
          "my_profile": "ملفي الشخصي",
          "partner_with_us": "كن شريكًا معنا",
          "contact_us": "اتصل بنا",
          "report_issue": "الإبلاغ عن مشكلة",
          "terms_conditions": "الشروط والأحكام",
          "rate": "تقييم",
          "more": "المزيد",
          "delete_account": "حذف الحساب",
          "delete_no_longer_use": "لا أستخدم التطبيق بعد الآن.",
          "delete_found_alternative": "وجدت بديلاً أفضل.",
          "delete_multiple_accounts": "لديّ حسابات متعددة.",
          "delete_technical_issues": "أواجه مشكلات تقنية.",
          "delete_difficult_use": "أجد التطبيق صعب الاستخدام.",
          "delete_not_useful": "لا أجد التطبيق مفيدًا بعد الآن.",
          "delete_missing_features":
              "التطبيق لا يحتوي على الميزات التي أحتاجها.",
          "delete_different_service": "أنتقل إلى خدمة مختلفة.",
          "delete_reduce_screen_time": "أحاول تقليل وقت الشاشة.",
          "delete_achieved_goals": "لقد حققت أهدافي باستخدام التطبيق.",
          "delete_other": "أخرى.",
          "account_deactivated": "تم إلغاء تنشيط حسابك.",
          "deactivation_decision":
              "إذا كنت تعتقد أن هذا القرار غير مبرر، يرجى الاتصال بنا.",
          "deactivation_reason": "تم إلغاء تنشيط حسابك للأسباب التالية: ",
          "courier_information": "معلومات المرسل",
          "date_price": "التاريخ والسعر",
          "delivery_id": "معرف التسليم: ",
          "package_details": "تفاصيل الطرد",
          "delivery_details": "تفاصيل التسليم",
          "male": "ذكر",
          "female": "أنثى",
          "accepted": "مقبول",
          "recovered": "مسترد",
          "delivered": "تم التوصيل",
          "onFeet": "على الأقدام",
          "car": "سيارة",
          "bicycle": "دراجة",
          "motorcycle": "دراجة نارية",
          "open": "مفتوح",
          "closed": "مغلق",
          "low": "منخفض",
          "high": "مرتفع",
          "medium": "متوسط",
          "you": "أنت",
          "support": "الدعم",
          "delivery": "توصيل",
          "account": "حساب",
          "subscription": "اشتراك",
          "others": "أخرى",
          "code_sent": "تم إرسال الرمز",
          "retryButton": "إعادة المحاولة",
          "conTryAgain": "تحقق من الاتصال وأعد المحاولة",
          "tryAgain": "أعد المحاولة",
          "connectionFailed": "فشل الاتصال",
          "updateRequiredTitle": "مطلوب تحديث",
          "updateButton": "تحديث",
          "updateRequiredDesc":
              "يوجد إصدار جديد من هذا التطبيق. يرجى التحديث للاستمرار في استخدامه.",
          "cancelDelivery": "إلغاء الطلبية",
          "whyCancel": "لماذا تريد إلغاء هذه الطلبية؟",
          'cancelRequest': 'إلغاء طلب التوصيل',
          'cancelRequestDesc': 'هل أنت متأكد من أنك تريد إلغاء التوصيل؟',
          'cancelDeliveryDesc':
              'هل أنت متأكد من أنك تريد إلغاء التوصيل؟ قد تؤدي الإلغاءات المتكررة إلى تعطيل حسابك مؤقتًا.',
          'cancelDeliveryChangeMind': 'غيرت رأيي',
          'cancelDeliveryLong': 'التوصيل يستغرق وقتًا طويلاً',
          'cancelDeliveryAddressIncorrect': 'عنوان التوصيل غير صحيح',
          'cancelDeliveryPackageNoNeeded': 'لم تعد هناك حاجة إلى الطرد',
          'cancelDeliveryIncorrectItem': 'عناصر الطلب غير صحيحة',
          'cancelDeliveryMySelf': 'أفضل استلامها بنفسي',
          'cancelDeliveryOther': 'أخرى',
          'goBackButton': 'العودة',
          'confirmButton': 'تأكيد',
          'deliveryCanceled': 'تم إلغاء التوصيل',
          'deliveryCanceledDesc':
              'تم إلغاء التوصيل من قبل العميل. إذا واجهت أي مشاكل، يمكنك الإبلاغ عنها للحصول على مساعدة إضافية.',
          'callCourier': 'اتصل بالساعي',
          'callCourierDesc': 'أنت على وشك إجراء مكالمة هاتفية مع الساعي.',
          'callButton': 'اتصل',
          'copyNumber': 'نسخ',
        }
      };
}
